name: Linux

on:
  push:
    branches:
      - '**'
    tags:
      - 'v*'
  pull_request:

jobs:
  build:
    strategy:
      matrix:
        include:
          - runner: ubuntu-latest
            name: x86_64
          - runner: ubuntu-24.04-arm
            name: aarch64

    name: ${{ matrix.name }}
    runs-on: ${{ matrix.runner }}

    steps:
    - uses: actions/checkout@v5
      with:
        submodules: recursive
    - uses: actions-rust-lang/setup-rust-toolchain@v1
      with:
        toolchain: nightly
    - uses: actions/setup-node@v6
      with:
        node-version: 24
    - run: sudo apt-get install clang -y
      

    - name: Build
      run: |
       cargo build --release
       pushd moonlight-web/web-server
       npm install
       npm run build
       mv dist static
       popd

       mv target/release/streamer streamer
       mv target/release/web-server web-server
       mv moonlight-web/web-server/static static


    - name: Upload build artifact
      uses: actions/upload-artifact@v4
      with:
        name: moonlight-web-${{ matrix.name }}-unknown-linux-gnu
        path: |
          streamer
          web-server
          static

  docker:
    name: Docker ${{ matrix.name }}
    needs: build

    if: startsWith(github.ref, 'refs/tags/v')

    strategy:
      matrix:
        include:
          - runner: ubuntu-latest
            arch: x86_64
            platform: amd64
          - runner: ubuntu-24.04-arm
            arch: aarch64
            platform: arm64

    runs-on: ${{ matrix.runner }}

    steps:
      - uses: actions/checkout@v4

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: moonlight-web-${{ matrix.arch }}-unknown-linux-gnu
          path: ./docker/moonlight-web

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./docker/
          file: ./docker/Dockerfile.action
          tags: mrcreativ3001/moonlight-web-stream:${{ github.ref_name }}-${{ github.run_id }}-${{ matrix.platform }}
          push: true

  docker-manifest:
    name: Docker create multi-arch manifest for versioned images
    runs-on: ubuntu-latest

    needs: docker
    if: startsWith(github.ref, 'refs/tags/v')

    steps:
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Create and push manifest
        run: |
          docker manifest create mrcreativ3001/moonlight-web-stream:test-${{ github.run_id }} \
            --amend mrcreativ3001/moonlight-web-stream/${{ github.ref_name }}-${{ github.run_id }}-amd64 \
            --amend mrcreativ3001/moonlight-web-stream/${{ github.ref_name }}-${{ github.run_id }}-arm64

          docker manifest push mrcreativ3001/moonlight-web-stream:${{ github.ref_name }}-${{ github.run_id }}

  docker-manifest-latest:
    name: Docker point latest image to versioned image
    runs-on: ubuntu-latest

    needs: docker
    if: "!contains(github.ref_name, '-prerelease')"

    steps:
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Create and push manifest
        run: |
          docker manifest create mrcreativ3001/moonlight-web-stream:latest \
            --amend mrcreativ3001/moonlight-web-stream:${{ github.ref_name }}

          docker manifest push mrcreativ3001/moonlight-web-stream:latest